# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_common.ipynb.

# %% auto 0
__all__ = ['T', 'fst', 'snd', 'group_by', 'partition', 'first', 'second', 'take_n', 'dt_str_now', 'date_str_now',
           'datetime_to_stamp', 'list_concat']

# %% ../nbs/00_common.ipynb 2
from collections import defaultdict
from typing import Any, Callable, Iterable

def group_by(grouper: Callable, items: Iterable[Any]) -> dict[any, any]:
    """Group items by a given function.

    Args:
        grouper (Callable): A function that returns a key to group by.
        items (Iterable[Any]): A list of items to be grouped.

    Returns:
        A dictionary with the grouped items.
    """
    groups = defaultdict(list)
    for item in items:
        groups[grouper(item)].append(item)
    return groups

# %% ../nbs/00_common.ipynb 3
from typing import Callable, TypeVar

T = TypeVar("T")
type Predicate[T] = Callable[[T], bool]


def partition(
    criterion: Predicate[T],
    items: Iterable[T],
) -> tuple[list[T], list[T]]:
    """Apply `criterion` to `items` to generate a list of those matching and not matching.

    Args:
        criterion (Predicate[T]): A function that returns True if the item meets the criterion.
        items (Iterable[T]): A list of items to be partitioned.

    Returns:
        A tuple containing two lists: one with items that meet the criterion and one with items that do not.
    """
    matches, misses = [], []
    for item in items:
        if criterion(item):
            matches.append(item)
        else:
            misses.append(item)

    return matches, misses

# %% ../nbs/00_common.ipynb 6
def first(iterable):
    """Returns the first item in an iterable"""
    _it = iter(iterable)
    return next(_it)
def second(iterable):
    """Returns the second item in an iterable"""
    _it = iter(iterable)
    next(_it)
    return next(_it)
fst = first
snd = second

# %% ../nbs/00_common.ipynb 7
from itertools import takewhile
from typing import Iterable

def take_n(iterable: Iterable, *, n: int = 5) -> Iterable:
    """Take n items from an iterable.

    Args:
        iterable (Iterable): The iterable to take items from.
        n (int, optional): The number of items to take. Defaults to 5.

    Yields:
        The next item in the iterable.
    """
    count = 0
    for x in takewhile(lambda _: count < n, iterable):
        yield x
        count += 1


# %% ../nbs/00_common.ipynb 9
from datetime import datetime, UTC

def dt_str_now() -> str:
    """Get the current time as a string in the format YYYY-MM-DD-HHMM"""
    return datetime.now(UTC).strftime("%Y-%m-%d-%H%M")

def date_str_now() -> str:
    """Export a date string year-month-day"""
    return datetime.now(UTC).strftime("%Y-%m-%d")

def datetime_to_stamp(dt: datetime = None) -> str:
    """Convert datetime to format YYYYMMDDHHMM (e.g. 202507171140).

    Args:
        dt (datetime, optional): The datetime object to convert. Defaults to None, in which case the current time is used.

    Returns:
        A string representation of the datetime in YYYYMMDDHHMM format.
    """
    if dt is None:
        dt = datetime.now()
    return dt.strftime("%Y%m%d%H%M")

# Usage example
# stamp = datetime_to_stamp(datetime(2025, 7, 17, 11, 40))  # Returns '202507171140'
# stamp = datetime_to_stamp()  # Returns current time in YYYYMMDDHHMM format


# %% ../nbs/00_common.ipynb 10
def list_concat(lists: list[list]) -> list:
    """Concatenate a list of lists into a single list.

    Args:
        lists (list[list]): A list of lists to concatenate.

    Returns:
        A single list containing all the items from the input lists.
    """
    result = [item for l_ in lists for item in l_]
    return result
