# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06_timeseries_stats.ipynb.

# %% auto 0
__all__ = ['add_step_columns', 'TypedSegment', 'AssociatedTrialRetyped', 'split_segment', 'retype_associated_data',
           'global_summary', 'rolling_summary', 'fixation_segments', 'aoi_from_fixations', 'trajectory_iou']

# %% ../../nbs/06_timeseries_stats.ipynb 3
from pathlib import Path
import polars as pl
from shapely.geometry import Polygon, MultiPoint


def add_step_columns(df: pl.DataFrame,
                     *,
                     x_col:str="X",
                     y_col:str="Y") -> pl.DataFrame:
    """
    Add delta_dist and angle to the DataFrame.
    Assumes rows are already sorted by `t`.
    """
    return (
        df.with_columns(
            delta_x=pl.col(x_col).diff().fill_null(0.0),
            delta_y=pl.col(y_col).diff().fill_null(0.0),
        )
        .with_columns(
            delta_dist=(pl.col("delta_x") ** 2 + pl.col("delta_y") ** 2).sqrt(),
            angle=pl.arctan2(pl.col("delta_y"), pl.col("delta_x")),
        )
        .drop(["delta_x", "delta_y"])
    )


# %% ../../nbs/06_timeseries_stats.ipynb 7
# TODO(stephen): move to the correct module -> data.segmentation
from dataclasses import dataclass # FIXME: dataclass versus namedtuple. Former is clearer, latter is faster.
from ..timeseries_segmentation import AssociatedTrialSegements

@dataclass
class TypedSegment:
    re: pl.DataFrame # realeye
    tobii: pl.DataFrame # tobii

@dataclass
class AssociatedTrialRetyped:
    trial_name: str
    segments: list[TypedSegment]

def split_segment(segment_df: pl.DataFrame) -> TypedSegment:
    "Split the 5 columns (timestamp, X, Y, X_re, Y_re) two ways, into RealEye and Tobii parts, sharing time"
    new_names = {"timestamp": "t"}
    return TypedSegment(
        segment_df.select("timestamp", "X_re", "Y_re").rename(new_names |{"X_re": "X", "Y_re": "Y"}),
        segment_df.select("timestamp", "X", "Y").rename(new_names)
    )

def retype_associated_data(data: AssociatedTrialSegements) -> AssociatedTrialRetyped:
    return AssociatedTrialRetyped(
        data.trial_name_or_id,
        [split_segment(seg) for seg in data.segments]
    )

# %% ../../nbs/06_timeseries_stats.ipynb 14
def global_summary(df: pl.DataFrame,
                   *,
                   x_col: str = "X",
                   y_col: str = "Y") -> pl.DataFrame:
    """
    Return a single-row DataFrame with global trajectory statistics.
    """
    return df.select(
        total_distance=pl.col("delta_dist").sum(),
        avg_speed=pl.col("delta_dist").mean(),
        std_speed=pl.col("delta_dist").std(),
        min_speed=pl.col("delta_dist").min(),
        max_speed=pl.col("delta_dist").max(),
        net_displacement=(
            (pl.col(x_col).last() - pl.col(x_col).first()) ** 2
            + (pl.col(y_col).last() - pl.col(y_col).first()) ** 2
        ).sqrt(),
        total_time=pl.col("t").last() - pl.col("t").first(),
        sinuosity=(
            pl.col("delta_dist").sum()
            / (
                (pl.col(x_col).last() - pl.col(x_col).first()) ** 2
                + (pl.col(y_col).last() - pl.col(y_col).first()) ** 2
            ).sqrt()
        ),
    )


# %% ../../nbs/06_timeseries_stats.ipynb 18
def rolling_summary(df: pl.DataFrame, window: int) -> pl.DataFrame:
    """
    Rolling statistics on speed and angle.
    """
    return (
        df.with_columns(
            roll_speed_mean=pl.col("delta_dist")
            .rolling_mean(window_size=window, min_samples=1)
            .alias("speed_mean"),
            roll_speed_std=pl.col("delta_dist")
            .rolling_std(window_size=window, min_samples=1)
            .alias("speed_std"),
            roll_angle_mean=pl.col("angle")
            .rolling_mean(window_size=window, min_samples=1)
            .alias("angle_mean"),
            roll_angle_std=pl.col("angle")
            .rolling_std(window_size=window, min_samples=1)
            .alias("angle_std"),
        )
        # Optionally drop the helper columns here if you only want the stats
    )

# %% ../../nbs/06_timeseries_stats.ipynb 22
def fixation_segments(
    df: pl.DataFrame,
    radius: float,
    *,
    x: str = "x",
    y: str = "y",
    t: str = "t",
    min_fixation_time: float | None = None,
    min_n_points: int = 1,
) -> pl.DataFrame:
    """
    Detect contiguous *fixation* segments in an eye-tracking trace.

    A fixation starts when the gaze stays **within `radius` units** from the
    *anchor* point of that fixation for at least `min_fixation_time`
    seconds (or `min_n_points` samples).  While the anchor is fixed,
    every new point is tested against this anchor.  As soon as a point
    exceeds the radius, the current fixation ends and a new anchor is set
    at that point.

    Parameters
    ----------
    df : pl.DataFrame
        Must contain the columns `x`, `y`, and `t` (units are your own).
    radius : float
        Spatial tolerance (in the same units as x, y).
    x, y, t : str
        Column names for the spatial and temporal coordinates.
    min_fixation_time : float, optional
        Minimum duration (in the same units as `t`) for a segment to be
        retained.  If None, `min_n_points` is the only filter.
    min_n_points : int, default 1
        Minimum number of consecutive points inside the radius.

    Returns
    -------
    pl.DataFrame
        One row per fixation segment with columns:
        fixation_id   – unique id per fixation (monotonic)
        t_start    – first timestamp of the fixation
        t_end      – last timestamp of the fixation
        x_anchor   – x-coordinate of the anchor point
        y_anchor   – y-coordinate of the anchor point
        duration   – t_end - t_start
        n_points   – number of rows in the fixation
    """
    if df.is_empty():
        return pl.DataFrame(
            {
                "fixation_id": pl.Series(dtype=pl.Int64),
                "t_start": pl.Series(dtype=pl.Int64),
                "t_end": pl.Series(dtype=pl.Int64),
                "x_anchor": pl.Series(dtype=pl.Float64),
                "y_anchor": pl.Series(dtype=pl.Float64),
                "n_points": pl.Series(dtype=pl.Int64),
                "duration": pl.Series(dtype=pl.Int64),
            }
        )

    # Ensure ascending order
    df = df.sort(t)
    df = df.with_row_index(name="i")

    # Convert to Python dicts for iteration
    rows = df.to_dicts()
    fixations = []
    if not rows:
        return pl.DataFrame(fixations)

    # Initial anchor point
    current_fix_start_idx = 0
    anchor_x = rows[0][x]
    anchor_y = rows[0][y]

    for i in range(1, len(rows)):
        dist = ((rows[i][x] - anchor_x) ** 2 + (rows[i][y] - anchor_y) ** 2) ** 0.5
        if dist > radius:
            # End of fixation, record it
            fixations.append(
                {
                    "i_start": rows[current_fix_start_idx]["i"],
                    "i_end": rows[i - 1]["i"],
                    "x_anchor": anchor_x,
                    "y_anchor": anchor_y,
                }
            )
            # New fixation starts at current point
            current_fix_start_idx = i
            anchor_x = rows[i][x]
            anchor_y = rows[i][y]

    # Add the last fixation
    fixations.append(
        {
            "i_start": rows[current_fix_start_idx]["i"],
            "i_end": rows[-1]["i"],
            "x_anchor": anchor_x,
            "y_anchor": anchor_y,
        }
    )

    # Convert back to polars DataFrame
    fix_df = pl.from_dicts(fixations)

    # Join with original data to get times and counts
    fix_df = fix_df.join(
        df.select(["i", t]).rename({"i": "i_start", t: "t_start"}),
        on="i_start",
    ).join(
        df.select(["i", t]).rename({"i": "i_end", t: "t_end"}),
        on="i_end",
    )

    # Calculate n_points and duration
    fix_df = fix_df.with_columns(
        n_points=pl.col("i_end") - pl.col("i_start") + 1,
        duration=pl.col("t_end") - pl.col("t_start"),
    ).drop(["i_start", "i_end"])

    # Apply filters
    if min_fixation_time is not None:
        fix_df = fix_df.filter(pl.col("duration") >= min_fixation_time)
    fix_df = fix_df.filter(pl.col("n_points") >= min_n_points)

    # Finalize
    return fix_df.with_row_index(name="fixation_id").select(
        [
            "fixation_id",
            "t_start",
            "t_end",
            "x_anchor",
            "y_anchor",
            "n_points",
            "duration",
        ]
    )


# %% ../../nbs/06_timeseries_stats.ipynb 31
def aoi_from_fixations(
    fixations: pl.DataFrame, eps: float, min_samples: int
) -> pl.DataFrame:
    """
    Identify Areas of Interest (AOIs) from fixation data using DBSCAN.

    Parameters
    ----------
    fixations : pl.DataFrame
        A DataFrame of fixation data, as returned by `fixation_segments`.
        Must contain `x_anchor` and `y_anchor` columns.
    eps : float
        The maximum distance between two samples for one to be considered
        as in the neighborhood of the other.
    min_samples : int
        The number of samples in a neighborhood for a point to be
        considered as a core point.

    Returns
    -------
    pl.DataFrame
        A DataFrame with AOI statistics, including the number of fixations
        in each AOI, the total duration, and the bounding box of the AOI.
    """
    try:
        from sklearn.cluster import DBSCAN

        failed_import = False
    except ImportError:
        failed_import = True

    if fixations.is_empty() or failed_import:
        return pl.DataFrame(
            {
                "aoi_id": pl.Series(dtype=pl.Int64),
                "n_fixations": pl.Series(dtype=pl.Int64),
                "total_duration": pl.Series(dtype=pl.Int64),
                "x_min": pl.Series(dtype=pl.Float64),
                "y_min": pl.Series(dtype=pl.Float64),
                "x_max": pl.Series(dtype=pl.Float64),
                "y_max": pl.Series(dtype=pl.Float64),
            }
        )

    # Extract anchor points for clustering
    coords = fixations.select(["x_anchor", "y_anchor"]).to_numpy()

    # Perform DBSCAN clustering
    db = DBSCAN(eps=eps, min_samples=min_samples).fit(coords)
    labels = db.labels_

    # Add cluster labels to fixations DataFrame
    fixations = fixations.with_columns(aoi_id=pl.Series(labels))

    # Filter out noise points (label -1)
    aois = fixations.filter(pl.col("aoi_id") != -1)

    # Aggregate statistics per AOI
    aoi_stats = aois.group_by("aoi_id").agg(
        n_fixations=pl.len(),
        total_duration=pl.col("duration").sum(),
        x_min=pl.col("x_anchor").min(),
        y_min=pl.col("y_anchor").min(),
        x_max=pl.col("x_anchor").max(),
        y_max=pl.col("y_anchor").max(),
    )

    return aoi_stats.sort("aoi_id")


# %% ../../nbs/06_timeseries_stats.ipynb 33
def trajectory_iou(
    traj1: pl.DataFrame,
    traj2: pl.DataFrame,
    *,
    x_col: str = "X",
    y_col: str = "Y",
) -> float:
    """
    Calculate the Intersection over Union (IoU) of two trajectories.

    The IoU is calculated based on the convex hulls of the trajectories.

    Parameters
    ----------
    traj1 : pl.DataFrame
        DataFrame for the first trajectory. Must contain `x_col` and `y_col`.
    traj2 : pl.DataFrame
        DataFrame for the second trajectory. Must contain `x_col` and `y_col`.
    x_col : str, default "X"
        Name of the column containing x-coordinates.
    y_col : str, default "Y"
        Name of the column containing y-coordinates.

    Returns
    -------
    float
        The IoU value, between 0.0 and 1.0.
    """
    # Extract points and create MultiPoint objects
    points1 = traj1.select([x_col, y_col]).to_numpy()
    points2 = traj2.select([x_col, y_col]).to_numpy()

    if len(points1) < 3 or len(points2) < 3:
        return 0.0

    # Compute convex hulls
    poly1 = MultiPoint(points1).convex_hull
    poly2 = MultiPoint(points2).convex_hull

    # Ensure polygons are valid
    if not poly1.is_valid or not poly2.is_valid:
        return 0.0

    # Calculate intersection and union
    intersection_area = poly1.intersection(poly2).area
    union_area = poly1.union(poly2).area

    if union_area == 0:
        return 0.0

    return intersection_area / union_area
