# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_image_gen_by_segments.ipynb.

# %% auto 0
__all__ = ['AssociatedTrialSegements', 'join_chunks_as_segments', 'select_trial', 'render_point_stream_video_with_opencv',
           'run_video_generation']

# %% ../../nbs/05_image_gen_by_segments.ipynb 3
import polars as pl
from pathlib import Path

# %% ../../nbs/05_image_gen_by_segments.ipynb 5
from typing import NamedTuple

class AssociatedTrialSegements(NamedTuple):
    trial_name_or_id: str
    segments: list[pl.DataFrame]

# %% ../../nbs/05_image_gen_by_segments.ipynb 6
from typing import Literal

_AsOfStrategy = Literal["backward", "forward", "nearest"]  # AsofStrategy (polars')
_NullStrategy = Literal["drop", "forward", "backward", "complex"] # Null Strategy (ours)
def join_chunks_as_segments(
    associated_chunks: list[tuple[pl.DataFrame, list[pl.DataFrame]]],
    *,
    join_strategy: _AsOfStrategy ="backward",
    null_handling: _NullStrategy="drop",
    keep_joining_column=False,
) -> list[AssociatedTrialSegements]:
    """Segment Tobii dataframes with corresponding RealEye dataframes.
     
    Assumes both have "timestamp" column, accurate to the millisecond (at least) per coordinate.

    Algorithm:
        given a list of tuple[pl.DataFrame, list[pl.DataFrame]] representing tobii and RealEye, resp.
        for each RE dataframe
            join with Tobii "master" frame on the "timestamp" column
            - "how" should be something like "nearest", or "between" the start and end of the RE df in question
            - rename the RE columns "X_re" and "Y_re"
            - drop the "test_created_at" column
            - filter all the nulls, and those outside of the time bounds of the RE df

    Arguments:
        associated_chunks: list of matched tobii dataframe with all the RE dataframes per stimulus
        join_strategy: strategy for joining the "timestamp" columns of the associated chunks. One of 
            Essentially, whether to look "backward", "forward", or to the "nearest" value when filling in the RealEye values.
            - backward: a future RealEye value will be matched to the last Tobii row before it chronologically
            - forward: a past RealEye value will be matched to the first Tobii row after it chronologically
            - nearest: RealEye values seek to minimize the time to the Tobii value, thereby finding the "nearest" match
            
            See pl.DataFrame.join_asof() documentation for the nuanced details.
            (https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.join_asof.html#polars.DataFrame.join_asof)
        null_handling: strategy to fill in the null values in Tobii data. Strategy can be one of
            - drop: drop/cut the rows (both Tobii and RealEye) that 
            - forward: forward fill any nulls with the last seen non-null value
            - backward: back fill from the first/next non-null value
            - complex: In our experience, the nulls were at the head and tail of the sequence, so this performs a back fill
                before a subsequent forward fill.
        keep_joining_column: whether to keep the RealEye timestamps (called "timestamp_right") after the data are aligned
            and merged into a single dataframe.
    Returns:
        subsegments of the Tobii df joined on the time column of the RE df, per the algorithm, of at least 5 columns
        - timestamp
        - X, Y: coordinates for the Tobii data points
        - X_re, Y_re: coordinates for the RealEye data points, 
    """
    output = []
    for tobii_df, re_dfs in associated_chunks:
        trial_name = tobii_df["source_tsv"][0]
        re_rename = dict(X="X_re", Y="Y_re")
        tobii_df = tobii_df.drop("source_tsv")
        segmented_associations = []
        for re_df in re_dfs:
            # NOTE: may need to use the `tolerance` kwarg to better tune the match-up
            associated = tobii_df.join_asof(
                re_df.select("timestamp", "X", "Y").rename(re_rename),
                on="timestamp",
                strategy=join_strategy,
                coalesce=(not keep_joining_column)
            )
            associated = associated.filter(
                (pl.col("timestamp") >= re_df["timestamp"].min())
                & (pl.col("timestamp") <= re_df["timestamp"].max())
            )
            # associated.drop_nulls(["X", "Y"])
            match null_handling:
                case "backward":
                    associated = associated.fill_null(strategy="backward")
                case "forward":
                    associated = associated.fill_null(strategy="forward")
                case "drop":
                    # NOTE: important to make sure Tobii's nothing don't crowd in
                    # NOTE: this can be 10% of the data and shouldn't be done lightly.
                    associated = associated.drop_nulls()
                case "complex":
                    associated = (associated
                                  .fill_null(strategy="forward")
                                  .fill_null(strategy="backward"))

            segmented_associations.append(associated)

        output.append(AssociatedTrialSegements(trial_name, segmented_associations))
    return output



# %% ../../nbs/05_image_gen_by_segments.ipynb 11
def select_trial(trial_name: str, joined_segments: list[AssociatedTrialSegements]):
    """Select a trial by name from a list of joined segments."""
    results = list(
        filter(lambda association: association.trial_name_or_id == trial_name, joined_segments)
    )
    if not results:
        raise ValueError(f"Unable to find trial with name {trial_name}")

    return results[0]

# %% ../../nbs/05_image_gen_by_segments.ipynb 14
import cv2

def render_point_stream_video_with_opencv(
    stimulus_image_paths: list[str],
    tobii_re_merge: AssociatedTrialSegements,
    *,
    export_fps=30,  # 4 minutes at 1 point per second
    output_file_name="animation",
    n_images_to_show: int = None,
):
    """Render a video from a stream of points using OpenCV."""
    if n_images_to_show is None:
        n_images_to_show = len(stimulus_image_paths)

    IMAGE_WIDTH, IMAGE_HEIGHT = 1920, 1080
    TARGET_DIMS = (IMAGE_WIDTH, IMAGE_HEIGHT)
    # --- Define colors in BGR format ---
    # For RED, you want the Red channel (index 2) to be 255.
    COLOR_RED = (0, 0, 255) 
    # For BLUE, you want the Blue channel (index 0) to be 255.
    COLOR_BLUE = (255, 0, 0)

    # 1. Set up the VideoWriter object from OpenCV
    # 'mp4v' is a common codec for .mp4 files.
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    output_name_on_disk = f"{output_file_name}.mp4"
    Path(output_name_on_disk).parent.mkdir(exist_ok=True, parents=True)
    video_writer = cv2.VideoWriter(output_name_on_disk, fourcc, export_fps, (IMAGE_WIDTH, IMAGE_HEIGHT))

    if not video_writer.isOpened():
        print("Error: Could not open video writer.")
        return

    # Pre-load all images into memory to avoid repeated disk I/O
    print("Pre-loading images...")
    images_in_memory = {path: cv2.imread(path) for path in stimulus_image_paths[:n_images_to_show]}
    print("Images loaded.")

    try:
        num_trials = min(n_images_to_show, len(stimulus_image_paths), len(tobii_re_merge.segments))
        
        # NOTE(stephen): num_trials is used to enforce control flow i.e. prevent unnecessary iterations in conjunction
        # with zip()'s default preference for the tuples
        for i_trial, img_path, tobii_re_xy in zip(range(num_trials),stimulus_image_paths, tobii_re_merge.segments):
            # Get the pre-loaded image data
            # NOTE: OpenCV loads images in BGR format, not RGB. Be mindful if matplotlib interactions...
            raw_image = images_in_memory[img_path]

            if raw_image is None:
                print(f"Warning: Could not load image {img_path}, skipping trial.")
                continue

            base_image = cv2.resize(raw_image, TARGET_DIMS, interpolation=cv2.INTER_AREA)
            print(f"Processing trial {i_trial+1}/{num_trials}...")
            
            # 2. Loop through the point data for this trial
            for _, tobii_X, tobii_Y, re_X, re_Y in tobii_re_xy.iter_rows():
                # --- This is the key performance difference ---
                # Create a fresh copy of the base image for this frame to draw on.
                # This is much faster than Matplotlib's full render pipeline.
                frame = base_image.copy()

                # Draw circles directly onto the NumPy array (the image frame).
                # This is a highly optimized C++ operation.
                # Point coordinates must be integers for cv2.
                # thickness = -1 fills the circle
                cv2.circle(frame, (int(re_X), int(re_Y)), radius=10, color=COLOR_RED, thickness=-1)
                cv2.circle(frame, (int(tobii_X), int(tobii_Y)), radius=10, color=COLOR_BLUE, thickness=-1)

                # 3. Write the modified frame to the video file
                video_writer.write(frame)
    finally:
        # 4. Release the video writer to finalize the file
        video_writer.release()
        print(f"Finished writing video to {output_name_on_disk}")



# %% ../../nbs/05_image_gen_by_segments.ipynb 15
from time import perf_counter
from ..common import date_str_now, dt_str_now


def run_video_generation(
    trial_name: str, *, joined_segments: list[AssociatedTrialSegements], stimuli_paths: list[Path], n_stimuli=3
):
    """Run the video generation process."""
    # prepared trial data that we're going to be turning into a video
    trial_data = select_trial(trial_name, joined_segments)

    hz_tobii = 120  # NOTE(stephen): unused
    export_fps = 60  # we can feel this but not see it precisely. 120 is ideal

    last_index = (n_stimuli if n_stimuli is not None else len(trial_data.segments)) - 1
    # sum the time of the segments based on the data in trial_segments.
    calculated_duration = (
        trial_data.segments[last_index]["timestamp"].max()
        - trial_data.segments[0]["timestamp"].min()
    ).total_seconds()

    print(f"""Exporting. 
FPS:      {export_fps}-fps (or as close as possible thereto)
Duration: {calculated_duration}-seconds
""")

    ts = dt_str_now()

    start_time = perf_counter()

    render_point_stream_video_with_opencv(
        stimuli_paths,
        trial_data,
        export_fps=export_fps,
        output_file_name=f"/Users/stephen/dev/RevChemData/{date_str_now()}-multi-image-video/{ts}-{trial_name}-timing-run",
        n_images_to_show=n_stimuli,
    )
    now = perf_counter()
    run_duration = now - start_time
    print(f"Full run (including image reload): {run_duration} seconds")
    print(f"Computed run efficiency {run_duration / calculated_duration = }")
